[package]
name = "pdbmol"
version = "0.1.0"
edition = "2021"
description = "Spec-compliant PDB(x)/mmCIF read/write library"
repository = "https://github.com/Yoshanuikabundi/pdbmol"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
pdbmol_cif = { path = "crates/pdbmol_cif" }
pdbmol_ccd = { path = "crates/pdbmol_ccd" }
pdbmol_pdb = { path = "crates/pdbmol_pdb" }
pdbmol_types = { path = "crates/pdbmol_types" }

[workspace]
members = ["crates/*"]

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
type_complexity = "allow"
should_implement_trait = "allow"
diverging_sub_expression = "allow"
needless_lifetimes = "allow"
let_unit_value = "allow"
